#!/usr/bin/env node
//
// scripts/hermes-setup.js
//
// Configures a Hermes Agent profile to run Athena.
//
//  - Verifies `hermes` binary is on PATH
//  - Writes ~/.hermes/cli-config.yaml that loads the Athena workspace
//    (SOUL.md / IDENTITY.md / AGENTS.md) as system prompt
//  - Writes ~/.hermes/.env with OPENROUTER_API_KEY + DISCORD_BOT_TOKEN
//  - Optionally registers Athena's nightly cron jobs against `hermes cron`
//
// Idempotent: re-running updates cli-config.yaml and .env without clobbering
// other Hermes state. Backs up any pre-existing cli-config.yaml that differs.
//
// Usage:
//   node scripts/hermes-setup.js                 # uses env vars from ~/.env.secrets
//   node scripts/hermes-setup.js --no-cron       # skip cron registration
//   node scripts/hermes-setup.js --dry-run       # print what it would write
//   node scripts/hermes-setup.js --persona icarus  # active persona other than athena
//

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const os = require('node:os');

const HOME = os.homedir();
const HERMES_HOME = process.env.HERMES_HOME || path.join(HOME, '.hermes');
const SECRETS_FILE = path.join(HOME, '.env.secrets');

const args = process.argv.slice(2);
const flags = {
  noCron: args.includes('--no-cron'),
  dryRun: args.includes('--dry-run'),
  persona: getFlagValue('--persona') || 'athena',
};

function getFlagValue(name) {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : null;
}

function log(msg) { process.stdout.write(`  ${msg}\n`); }
function ok(msg)  { process.stdout.write(`  \x1b[32m✓\x1b[0m ${msg}\n`); }
function warn(msg){ process.stdout.write(`  \x1b[33m⚠\x1b[0m ${msg}\n`); }
function die(msg) { process.stderr.write(`  \x1b[31m✗\x1b[0m ${msg}\n`); process.exit(1); }

function loadSecrets() {
  if (!fs.existsSync(SECRETS_FILE)) {
    die(`Secrets file not found at ${SECRETS_FILE}. Run install.sh first.`);
  }
  const raw = fs.readFileSync(SECRETS_FILE, 'utf8');
  const env = {};
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    env[key] = val;
  }
  return env;
}

function checkHermesBinary() {
  try {
    execFileSync('hermes', ['--version'], { stdio: 'pipe' });
    ok('hermes binary on PATH');
    return true;
  } catch {
    warn('hermes binary not found on PATH');
    log('Install Hermes:');
    log('  git clone https://github.com/nousresearch/hermes-agent.git ~/Apps/hermes-agent');
    log('  cd ~/Apps/hermes-agent && bash setup-hermes.sh');
    log('  source ~/Apps/hermes-agent/.venv/bin/activate');
    return false;
  }
}

function buildCliConfig(persona, model, workspaceBase) {
  const personaDir = path.join(workspaceBase, persona);
  const provider = pickProvider(model);
  return `# Hermes Agent CLI Configuration — Athena profile
# Generated by agent-athena/scripts/hermes-setup.js
# Re-run to regenerate. Hand edits to this file will be overwritten.

# =============================================================================
# Model
# =============================================================================
model:
  provider: "${provider}"
  default: "${model}"

# =============================================================================
# System prompt — Athena workspace persona
# =============================================================================
# Hermes loads these files as the persona's system prompt at session start.
# Edit the files (not this list) to evolve the agent's identity.
system_prompt:
  files:
    - "${path.join(personaDir, 'SOUL.md')}"
    - "${path.join(personaDir, 'IDENTITY.md')}"
    - "${path.join(personaDir, 'AGENTS.md')}"
    - "${path.join(personaDir, 'CLAUDE.md')}"
  include_workdir_agents_md: true

# =============================================================================
# Memory
# =============================================================================
memory:
  provider: "sqlite"
  path: "${path.join(HERMES_HOME, 'memory', `${persona}.db`)}"

# =============================================================================
# Sessions
# =============================================================================
sessions:
  dir: "${path.join(HERMES_HOME, 'sessions', persona)}"

# =============================================================================
# Skills — load Athena workspace skills + the other personas as dispatchable
# =============================================================================
skills:
  enabled:
    - "athena/core"
  search_paths:
    - "${path.join(personaDir, 'skills')}"
    - "${workspaceBase}"

# =============================================================================
# Terminal / execution
# =============================================================================
terminal:
  backend: "local"
  cwd: "${HOME}"
  timeout: 180

# =============================================================================
# Gateway / messaging
# =============================================================================
gateway:
  enabled: true
  platforms:
    discord:
      enabled: true
      channel_id_env: "DISCORD_${persona.toUpperCase()}_CHANNEL_ID"
  background_process_notifications: "result"
`;
}

function pickProvider(model) {
  if (!model) return 'openrouter';
  if (model.startsWith('anthropic/')) return 'anthropic';
  if (model.startsWith('openai/'))    return 'openai';
  if (model.startsWith('google/') || model.startsWith('gemini/')) return 'gemini';
  if (model.startsWith('ollama/'))    return 'ollama';
  return 'openrouter';
}

function buildHermesEnv(secrets) {
  const lines = [
    '# Hermes Agent .env — generated by agent-athena/scripts/hermes-setup.js',
    '# All secrets sourced from ~/.env.secrets. Edit there, then re-run setup.',
    '',
  ];
  const map = [
    ['OPENROUTER_API_KEY', secrets.OPENROUTER_API_KEY || secrets.CUSTOM_API_KEY || ''],
    ['ANTHROPIC_API_KEY',  secrets.ANTHROPIC_API_KEY  || ''],
    ['OPENAI_API_KEY',     secrets.OPENAI_API_KEY     || ''],
    ['GEMINI_API_KEY',     secrets.GEMINI_API_KEY     || ''],
    ['DISCORD_BOT_TOKEN',  secrets.DISCORD_BOT_TOKEN  || ''],
  ];
  for (const [key, val] of map) {
    if (val) lines.push(`${key}=${val}`);
  }
  for (const key of Object.keys(secrets)) {
    if (key.startsWith('DISCORD_') && key.endsWith('_CHANNEL_ID')) {
      lines.push(`${key}=${secrets[key]}`);
    }
  }
  return lines.join('\n') + '\n';
}

function writeFileWithBackup(target, content) {
  if (flags.dryRun) {
    log(`[dry-run] would write ${target} (${content.length} bytes)`);
    return;
  }
  if (fs.existsSync(target)) {
    const existing = fs.readFileSync(target, 'utf8');
    if (existing === content) {
      ok(`${path.basename(target)} unchanged`);
      return;
    }
    const backup = `${target}.bak.${Date.now()}`;
    fs.copyFileSync(target, backup);
    log(`backed up existing ${path.basename(target)} to ${path.basename(backup)}`);
  }
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, { mode: 0o600 });
  ok(`wrote ${target}`);
}

function copyWorkspacesToHermes(workspaceBase) {
  const openclawBase = path.join(HOME, '.openclaw', 'workspaces');
  if (!fs.existsSync(openclawBase) || workspaceBase === openclawBase) {
    return;
  }
  if (flags.dryRun) {
    log(`[dry-run] would mirror workspaces from ${openclawBase} to ${workspaceBase}`);
    return;
  }
  fs.mkdirSync(workspaceBase, { recursive: true });
  for (const entry of fs.readdirSync(openclawBase)) {
    const src = path.join(openclawBase, entry);
    const dst = path.join(workspaceBase, entry);
    if (!fs.statSync(src).isDirectory()) continue;
    if (fs.existsSync(dst)) continue;
    fs.cpSync(src, dst, { recursive: true });
  }
  ok(`mirrored workspaces to ${workspaceBase}`);
}

function registerCronJobs() {
  if (flags.noCron) {
    log('--no-cron: skipping cron registration');
    return;
  }
  if (flags.dryRun) {
    log('[dry-run] would register Hermes cron jobs');
    return;
  }
  const jobs = [
    { name: 'athena-nightly',    schedule: '0 23 * * *',   script: 'scripts/nightly-report.js' },
    { name: 'site-health',       schedule: '*/30 * * * *', script: 'scripts/site-health.js' },
    { name: 'session-cleanup',   schedule: '15 1 * * *',   script: 'scripts/session-cleanup.js' },
    { name: 'weekly-compaction', schedule: '0 23 * * 0',   script: 'scripts/weekly-compaction.js' },
    { name: 'cost-tracker',      schedule: '0 6 * * *',    script: 'scripts/cost-tracker.js' },
  ];
  for (const job of jobs) {
    try {
      execFileSync(
        'hermes',
        ['cron', 'add', '--name', job.name, '--schedule', job.schedule, '--script', job.script],
        { stdio: 'pipe' }
      );
      ok(`registered cron: ${job.name}`);
    } catch (err) {
      warn(`failed to register ${job.name}: ${(err.message || '').split('\n')[0]}`);
    }
  }
}

function main() {
  log('');
  log('Configuring Hermes Agent for Athena...');
  log('');

  if (!checkHermesBinary() && !flags.dryRun) {
    die('hermes binary required. Install per the instructions above, then re-run.');
  }

  const secrets = loadSecrets();
  const model = secrets.SELECTED_MODEL || 'anthropic/claude-sonnet-4-6';
  const workspaceBase = path.join(HERMES_HOME, 'workspaces');

  copyWorkspacesToHermes(workspaceBase);

  const cliConfigPath = path.join(HERMES_HOME, 'cli-config.yaml');
  const envPath = path.join(HERMES_HOME, '.env');

  writeFileWithBackup(cliConfigPath, buildCliConfig(flags.persona, model, workspaceBase));
  writeFileWithBackup(envPath, buildHermesEnv(secrets));

  registerCronJobs();

  log('');
  ok('Hermes Athena profile ready.');
  log('');
  log(`Active persona: ${flags.persona}`);
  log(`Profile home:   ${HERMES_HOME}`);
  log(`Workspaces:     ${workspaceBase}`);
  log('');
  log('Start the gateway:   hermes gateway start');
  log('Run interactively:   hermes');
  log('Switch persona:      node scripts/hermes-setup.js --persona <name>');
  log('');
}

try {
  main();
} catch (err) {
  die(err.stack || err.message);
}
