#!/usr/bin/env node
/**
 * skill-review.js
 * Weekly cron script that scans all agent workspaces for GOTCHAS.md,
 * NIGHTLY-NOTES.md, and daily memory files from the past week.
 * Compiles findings into SKILL-REVIEW.md in Athena's workspace.
 * Athena reads it and decides what agent rules to update.
 *
 * Usage: node skill-review.js [--dir /path/to/workspaces] [--days 7] [--dry-run]
 *
 * Cron: 0 22 * * 0 (Sunday 10pm, before weekly compaction)
 */

const fs = require('fs')
const path = require('path')

const args = process.argv.slice(2)
const dirIdx = args.indexOf('--dir')
const daysIdx = args.indexOf('--days')
const dryRun = args.includes('--dry-run')

const workspacesDir = dirIdx !== -1
  ? args[dirIdx + 1]
  : path.join(__dirname, '..', 'workspaces')
const lookbackDays = daysIdx !== -1 ? parseInt(args[daysIdx + 1], 10) : 7

const athenaDir = path.join(workspacesDir, 'athena')
const outputFile = path.join(athenaDir, 'SKILL-REVIEW.md')

const cutoff = new Date()
cutoff.setDate(cutoff.getDate() - lookbackDays)

function isRecentDate(dateStr) {
  const d = new Date(dateStr)
  return !isNaN(d.getTime()) && d >= cutoff
}

function readFileSafe(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8').trim()
  } catch {
    return null
  }
}

function getRecentMemoryEntries(memoryDir) {
  if (!fs.existsSync(memoryDir)) return []

  const entries = []
  const files = fs.readdirSync(memoryDir).filter(f => /^\d{4}-\d{2}-\d{2}\.md$/.test(f))

  for (const file of files) {
    const dateStr = file.replace('.md', '')
    if (isRecentDate(dateStr)) {
      const content = readFileSafe(path.join(memoryDir, file))
      if (content) {
        entries.push({ date: dateStr, content })
      }
    }
  }

  return entries.sort((a, b) => a.date.localeCompare(b.date))
}

function extractRecentGotchas(content) {
  if (!content) return null

  const lines = content.split('\n')
  const recent = []
  const datePattern = /\d{4}-\d{2}-\d{2}/

  for (const line of lines) {
    const match = line.match(datePattern)
    if (match && isRecentDate(match[0])) {
      recent.push(line.trim())
    }
  }

  return recent.length > 0 ? recent.join('\n') : null
}

function extractRecentNightlyNotes(content) {
  if (!content) return null

  const sections = content.split(/^## /m).filter(Boolean)
  const recent = []
  const datePattern = /\d{4}-\d{2}-\d{2}/

  for (const section of sections) {
    const match = section.match(datePattern)
    if (match && isRecentDate(match[0])) {
      recent.push('## ' + section.trim())
    }
  }

  return recent.length > 0 ? recent.join('\n\n') : null
}

// Scan all agent workspaces
const agentDirs = fs.readdirSync(workspacesDir).filter(name => {
  const full = path.join(workspacesDir, name)
  return fs.statSync(full).isDirectory() && name !== 'office'
})

// Also scan office agent workspaces
const officeDir = path.join(workspacesDir, 'office')
const officeDirs = fs.existsSync(officeDir)
  ? fs.readdirSync(officeDir).filter(name => {
      return fs.statSync(path.join(officeDir, name)).isDirectory()
    }).map(name => ({ name: `office/${name}`, dir: path.join(officeDir, name) }))
  : []

const allAgents = [
  ...agentDirs.map(name => ({ name, dir: path.join(workspacesDir, name) })),
  ...officeDirs
]

const now = new Date().toISOString().split('T')[0]
const sections = []

let totalGotchas = 0
let totalNotes = 0
let totalMemory = 0

for (const agent of allAgents) {
  const agentSections = []

  // GOTCHAS.md
  const gotchasContent = readFileSafe(path.join(agent.dir, 'GOTCHAS.md'))
  const recentGotchas = extractRecentGotchas(gotchasContent)
  if (recentGotchas) {
    agentSections.push(`### GOTCHAS.md\n${recentGotchas}`)
    totalGotchas++
  }

  // NIGHTLY-NOTES.md
  const notesContent = readFileSafe(path.join(agent.dir, 'NIGHTLY-NOTES.md'))
  const recentNotes = extractRecentNightlyNotes(notesContent)
  if (recentNotes) {
    agentSections.push(`### NIGHTLY-NOTES.md\n${recentNotes}`)
    totalNotes++
  }

  // Daily memory files
  const memoryEntries = getRecentMemoryEntries(path.join(agent.dir, 'memory'))
  if (memoryEntries.length > 0) {
    const memorySection = memoryEntries
      .map(e => `#### ${e.date}\n${e.content}`)
      .join('\n\n')
    agentSections.push(`### Daily Memory\n${memorySection}`)
    totalMemory += memoryEntries.length
  }

  if (agentSections.length > 0) {
    sections.push(`## ${agent.name}\n\n${agentSections.join('\n\n')}`)
  }
}

// Build the output
const output = `# SKILL-REVIEW.md
> Auto-generated by skill-review.js on ${now}
> Covering the last ${lookbackDays} days (since ${cutoff.toISOString().split('T')[0]})

This file compiles recent failures, learnings, and patterns from all agent workspaces.
Athena: review this and decide which agent SOUL.md or AGENTS.md files need rule updates.

**Summary:** ${sections.length} agents with activity | ${totalGotchas} gotchas | ${totalNotes} nightly notes | ${totalMemory} memory entries

---

${sections.length > 0 ? sections.join('\n\n---\n\n') : '_No recent activity found across any agent workspace._'}

---

## Action Required

Review the above and:
1. Identify repeated failures or patterns across agents
2. Update the relevant agent's SOUL.md or AGENTS.md with new rules
3. Only add rules for real failures — no speculative rules
4. Log changes in today's memory file
`

if (dryRun) {
  console.log('--- DRY RUN ---')
  console.log(output)
  console.log(`\nWould write to: ${outputFile}`)
} else {
  fs.writeFileSync(outputFile, output, 'utf8')
  console.log(`✅ SKILL-REVIEW.md written to ${outputFile}`)
  console.log(`   ${sections.length} agents | ${totalGotchas} gotchas | ${totalNotes} nightly notes | ${totalMemory} memory entries`)
}
